name: Build (aarch64-linux)

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
  workflow_call:

permissions:
  contents: write

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Zig 🛎️
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Test 🔧
        shell: bash
        run: zig build test --summary all
      - name: Build 🔧
        run: |
          rm -rf build
          mkdir build
          cd build
          zig build-lib ../src/xxhash-ffi.zig -dynamic -OReleaseFast -target aarch64-linux
      - name: Upload Artifact 🚀
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-linux
          path: build/*